# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

WORKSPACE="Hamzter.xcworkspace"
PACKAGE_SCHEME="Hamzter"
TARGET_DEVICE="iPhone 14 Pro Max (16.1)"

platform :ios do
  desc "Running unit tests"
  lane :unit_test do
    scan(
      workspace: WORKSPACE,
      scheme: PACKAGE_SCHEME,
      device: TARGET_DEVICE
    )
  end
end
